apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - image: europe-north2-docker.pkg.dev/sleepr-497417/backend/notifications
          name: notifications
          env:
            - name: PORT
              value: '3000'
            - name: GOOGLE_OAUTH_CLIENT_ID
              value: 502090242397-0l1o9bgm4ebnggnmvle173qsg1eimte7.apps.googleusercontent.com
            - name: SMTP_USER
              value: sleepr.test19@gmail.com
            - name: GOOGLE_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google
                  key: clientSecret
            - name: GOOGLE_OAUTH_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: google
                  key: refreshToken
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          ports:
            - containerPort: 3000
